import "./globals.css";
import type { Metadata } from "next";
import Footer from './components/Footer';
import Header from './components/Header';
import { GeistSans } from 'geist/font/sans';
import { CartProvider } from "./components/CartContext";
import { WishlistProvider } from './components/WishContext'; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} min-h-screen flex flex-col`}>
        {/* Wrap with both CartProvider and WishlistProvider */}
        <CartProvider>
          <WishlistProvider>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
